export const CONCEPT_CANDIDATE_COUNT = 3
export const PALETTE_CANDIDATE_COUNT = 3
export const WIREFRAME_CANDIDATE_COUNT = 20
export const RECOMMENDED_WIREFRAME_COUNT = 3
export const COMPONENT_CANDIDATE_COUNT = 3
